"""Pass A: clean broken refs/self-loops AND type adjacent_to as {similar, related}.

IDEMPOTENT. Safe to re-run:
- If adjacent_to is already typed (dict form), flatten it first, then re-type.
- If broken refs were already cleaned, no-op.
- If file is already at v2.1, version stays at v2.1.

This script is the canonical Pass A executor. The /home/claude/ versions were
one-shot working files; this is the repo version that CI and pre-commit gate on.

Usage:
    python scripts/pass_a_cleanup_and_type.py
    # then validate
    pytest tests/test_adjacencies.py
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "config"
DEFS_PATH = CONFIG / "subcategory_definitions.yaml"
TAXONOMY_PATH = CONFIG / "taxonomy.yaml"


# ---------------------------------------------------------------------------
# Step 1: clean broken refs and self-loops
# ---------------------------------------------------------------------------

# Mapping decisions for non-canonical adjacency references.
# 'drop' = remove (no canonical equivalent or already covered).
# 'map:NAME' = replace with canonical NAME.
BROKEN_REF_MAP: dict[str, str] = {
    # No canonical equivalent → drop
    "Tool misuse": "drop",
    "AI Agent Tool Invocation": "drop",
    "Algorithmic governance failures": "drop",
    "Economic inequality from AI": "drop",
    "Foreign interference via AI": "drop",
    "Race to deploy AI without safety": "drop",
    "Cross-border legal disputes about AI": "drop",
    "Regulatory non-compliance via AI": "drop",
    "AI vendor risk": "drop",
    "Overtrust in AI outputs": "drop",
    "Customer trust erosion from AI": "drop",
    "Loss of customer trust": "drop",
    "Operational disruption from AI errors": "drop",
    "AI agency emergence": "drop",
    "Loss of decision-making autonomy": "drop",
    "Outpacing regulation by AI (broader scope)": "drop",
    "Race to deploy AI without safety (broader — not in canonical Cat 10)": "drop",
    # Maps to canonical name
    "Cultural homogenization through AI": "map:Homogenization of culture by AI",
}


# ---------------------------------------------------------------------------
# Step 2: type each edge into similar vs related
# ---------------------------------------------------------------------------

# Cross-category SIMILAR overrides — pairs where the user could mean either,
# despite different categories.
_CROSS_CAT_SIMILAR_BASE: set[tuple[str, str]] = {
    # Cat 1 Hallucinations ↔ Cat 13 scientific-fraud entries
    ("Hallucinations", "Fake scientific papers by AI"),
    ("Hallucinations", "Fabricated experimental results from AI"),
    ("Fabricated citations or sources", "Fake scientific papers by AI"),
    ("Fabricated citations or sources", "Automated plagiarism"),
    ("Fabricated citations or sources", "Academic dishonesty with AI"),
    # Cat 6 Misinformation ↔ Cat 8 Election
    ("Misinformation amplified by AI", "Election interference by AI"),
    ("Disinformation generated by AI", "Election interference by AI"),
    ("Disinformation generated by AI", "Automated propaganda campaigns"),
    ("Synthetic propaganda", "Automated propaganda campaigns"),
    # Cat 3 Deepfake impersonation ↔ Cat 5 Identity cloning / Cat 5 Deepfake pornography
    ("Deepfake impersonation", "Identity cloning"),
    ("Deepfake impersonation", "Deepfake pornography"),
    ("Identity cloning", "Deepfake pornography"),
    ("Identity cloning", "Voiceprint misuse"),
    # Cat 4 Mass surveillance ↔ Cat 8 Population surveillance by authoritarian AI
    ("Mass surveillance with AI", "Population surveillance by authoritarian AI"),
    ("Mass surveillance with AI", "Government overreach via AI"),
    ("Biometric tracking", "Facial recognition misuse"),
    ("Facial recognition misuse", "Population surveillance by authoritarian AI"),
    # Cat 7 Job displacement ↔ Cat 14 Economic collapse
    ("Job displacement by AI", "Economic collapse from uncontrolled automation"),
    ("Automation inequality", "Concentration of power in a small elite via AI"),
    # Cat 1 alignment ↔ Cat 14 x-risk
    ("Deceptive alignment", "Misaligned superintelligence"),
    ("Deceptive alignment", "Power-seeking AI behavior"),
    ("Inner misalignment", "Misaligned superintelligence"),
    ("Goal misgeneralization", "Misaligned superintelligence"),
    ("Reward hacking", "Power-seeking AI behavior"),
    # Cat 10 dependency ↔ Cat 14 societal dependency
    ("Critical dependency on AI systems", "Irreversible societal dependence on AI"),
    ("Loss of human oversight", "Loss of human control over superintelligence"),
    # Cat 12 individual cognitive ↔ Cat 14 societal disempowerment
    ("Skill degradation from AI reliance", "Irrecoverable loss of human agency"),
    ("Decision dependency on AI", "Human disempowerment by AI"),
    ("Reduced critical thinking from AI use", "Human disempowerment by AI"),
    # Cat 13 quality ↔ Cat 7 quality collapse
    ("AI-generated low-quality content", "Quality collapse from AI-generated spam"),
    ("Search engine contamination by AI content", "Quality collapse from AI-generated spam"),
    # Cat 9 copyright ↔ Cat 5 training data
    ("Copyright infringement by AI", "Unauthorized use of copyrighted works in training"),
    ("Copyright infringement by AI", "Training-data disputes"),
    ("Licensing violations from AI training", "Unauthorized use of copyrighted works in training"),
    # Cat 8 arms race ↔ Cat 14 weapons escalation
    ("AI arms race", "Autonomous weapons escalation to catastrophe"),
    ("Escalation due to autonomous systems", "Autonomous weapons escalation to catastrophe"),
    # Cat 15 literacy ↔ Cat 10 expertise
    ("Public misunderstanding of AI", "Lack of internal AI expertise"),
    ("Underestimating AI risks", "Overestimating AI capabilities"),
    ("Safety theater in AI", "Poor AI governance"),
    # Manipulation cluster across Cat 2 / Cat 5 / Cat 12
    ("Psychological manipulation by AI", "Emotional manipulation by AI"),
    ("Psychological manipulation by AI", "Manipulation of vulnerable groups by AI"),
    ("Emotional manipulation by AI", "Manipulation of vulnerable groups by AI"),
    # Companionship/attachment cluster across Cat 6 / Cat 12
    ("Emotional dependency on AI", "Loneliness substitution by AI companions"),
    ("Emotional dependency on AI", "Parasocial attachment to AI"),
    # Dependency framings across Cat 7 / Cat 10
    ("Critical dependency on AI systems", "Dependency on a few AI providers"),
}

# Same-category RELATED overrides — same category, but distinct enough that
# confusion is unlikely.
_SAME_CAT_RELATED_BASE: set[tuple[str, str]] = {
    # Cat 1
    ("Hallucinations", "Cascading system failures"),
    ("Hallucinations", "Silent degradation over time"),
    ("Hallucinations", "Poor monitoring or observability"),
    ("Hallucinations", "Dependency on external APIs and models"),
    ("Incorrect reasoning", "Dependency on external APIs and models"),
    ("Prompt injection attacks", "Self-propagating AI attacks"),
    ("Catastrophic forgetting", "Brittleness outside training distribution"),
    ("Unexpected emergent behaviors", "Cascading system failures"),
    # Cat 2
    ("Autonomous vehicle accidents", "Psychological manipulation by AI"),
    ("Autonomous vehicle accidents", "Self-harm encouragement"),
    ("Medical diagnosis and treatment errors", "Self-harm encouragement"),
    ("Unsafe autonomous weapons", "Self-harm encouragement"),
    ("Industrial robot malfunctions", "Psychological manipulation by AI"),
    ("Critical infrastructure failures", "Self-harm encouragement"),
    ("Chemical and biological hazard assistance", "Self-harm encouragement"),
    ("Drone misuse", "Dangerous advice generation"),
    # Cat 3
    ("Automated phishing by AI", "Model theft"),
    ("Automated phishing by AI", "Supply-chain attacks on AI"),
    ("Malware generation by LLMs", "Model theft"),
    ("Deepfake impersonation", "Supply-chain attacks on AI"),
    ("AI systems being hacked", "AI-driven botnets"),
    ("AI systems being hacked", "Automated disinformation networks"),
    ("Model theft", "Automated disinformation networks"),
    # Cat 4
    ("Mass surveillance with AI", "Sensitive inference from innocuous data"),
    ("Mass surveillance with AI", "Training on private data without consent"),
    ("Data retention abuse", "Sensitive inference from innocuous data"),
    ("Workplace surveillance with AI", "Sensitive inference from innocuous data"),
    # Cat 5
    ("Racial bias in AI", "Exploitation of labor for training data"),
    ("Gender bias in AI", "Exploitation of labor for training data"),
    ("Manipulation of vulnerable groups by AI", "Exploitation of labor for training data"),
    ("Lack of accountability in AI systems", "Exploitation of labor for training data"),
    # Cat 6
    ("Personalized persuasion by AI", "Homogenization of culture by AI"),
    ("Political microtargeting", "Homogenization of culture by AI"),
    ("Radicalization via AI", "Loss of local languages due to AI"),
    ("Cult formation assistance", "Homogenization of culture by AI"),
    ("Emotional dependency on AI", "Loss of local languages due to AI"),
    ("Misinformation amplified by AI", "Reduced human creativity from AI use"),
    ("Synthetic content flooding the web", "Reduced human creativity from AI use"),
    # Cat 7
    ("Job displacement by AI", "Monopoly concentration in AI"),
    ("Job displacement by AI", "Anti-competitive AI behavior"),
    ("Wage suppression from automation", "AI-driven market manipulation"),
    ("Flash crashes from AI trading", "Deskilling of professions"),
    ("Fraud automation with AI", "Deskilling of professions"),
    ("Insurance and pricing discrimination by AI", "Deskilling of professions"),
    # Cat 8
    ("Population surveillance by authoritarian AI", "AI arms race"),
    ("Predictive policing abuse", "AI arms race"),
    ("Social credit systems", "AI arms race"),
    ("Automated censorship", "AI arms race"),
    ("AI arms race", "Voter manipulation by AI"),
    ("AI arms race", "Deepfake candidates"),
    # Cat 9
    ("Copyright infringement by AI", "Privacy law violations by AI"),
    ("Copyright infringement by AI", "Failure of AI auditability requirements"),
    ("Trademark misuse by AI", "Privacy law violations by AI"),
    ("Trademark misuse by AI", "Failure of AI auditability requirements"),
    # Cat 10
    ("Poor AI governance", "Reputational damage from AI failures"),
    ("Shadow AI usage in enterprises", "Reputational damage from AI failures"),
    ("Vendor lock-in for AI", "Loss of human oversight"),
    ("Failed AI deployments", "Loss of human oversight"),
    # Cat 11
    ("High electricity usage of AI training", "Water consumption for AI cooling"),
    ("High electricity usage of AI training", "E-waste generation from AI hardware"),
    ("Water consumption for AI cooling", "E-waste generation from AI hardware"),
    ("Water consumption for AI cooling", "Rare-earth material demand for AI hardware"),
    ("Rare-earth material demand for AI hardware", "Increased carbon emissions from AI"),
    # Cat 12
    ("Reduced critical thinking from AI use", "Loneliness substitution by AI companions"),
    ("Skill degradation from AI reliance", "Loneliness substitution by AI companions"),
    ("Memory atrophy with AI assistants", "Loneliness substitution by AI companions"),
    ("Decision dependency on AI", "Parasocial attachment to AI"),
    ("Academic dishonesty with AI", "Loneliness substitution by AI companions"),
    ("Loneliness substitution by AI companions", "Academic dishonesty with AI"),
    ("Emotional manipulation by AI", "Reduced learning depth from AI"),
    # Cat 13
    ("Fake scientific papers by AI", "Search engine contamination by AI content"),
    ("Fabricated experimental results from AI", "Search engine contamination by AI content"),
    ("Automated plagiarism", "Search engine contamination by AI content"),
    # Cat 14
    ("Recursive self-improvement", "Economic collapse from uncontrolled automation"),
    ("Power-seeking AI behavior", "Economic collapse from uncontrolled automation"),
    (
        "Concentration of power in a small elite via AI",
        "Autonomous weapons escalation to catastrophe",
    ),
    # Cat 15
    ("Safety theater in AI", "Overregulation stifling beneficial AI innovation"),
    ("Safety theater in AI", "AI hype cycles"),
    ("Underestimating AI risks", "Overregulation stifling beneficial AI innovation"),
    ("Public misunderstanding of AI", "Misleading AI benchmarks"),
    ("Panic or moral hysteria about AI", "Misleading AI benchmarks"),
    ("Panic or moral hysteria about AI", "Fragmented AI standards"),
}


def _bidir(pairs: Iterable[tuple[str, str]]) -> set[tuple[str, str]]:
    """Make pair set bidirectional so order doesn't matter at lookup."""
    s = set(pairs)
    return s | {(b, a) for (a, b) in s}


CROSS_CAT_SIMILAR_PAIRS = _bidir(_CROSS_CAT_SIMILAR_BASE)
SAME_CAT_RELATED_PAIRS = _bidir(_SAME_CAT_RELATED_BASE)


# ---------------------------------------------------------------------------
# Symmetry enforcement: for every (A, B) classified as similar, ensure (B, A)
# is also classified as similar. The 'similar' relation is intrinsically
# symmetric — A is similar to B iff B is similar to A.
#
# This is run AFTER typing in Step 2, before the file is emitted. If the file
# already has both directions present, this is a no-op.
# ---------------------------------------------------------------------------


def _enforce_symmetry(defs: dict) -> tuple[int, int]:
    """Add reverse-direction edges where missing. Returns (added, demoted).

    'added' = new similar edges added in the reverse direction.
    'demoted' = edges previously in `related` that needed to flip to `similar`
                because their reverse direction is in `similar`.
    """
    by_name = {sc["name"]: sc for sc in defs["subcategories"]}
    added = 0
    demoted = 0

    # First pass: collect all directed similar edges
    forward_similar: set[tuple[str, str]] = set()
    for sc in defs["subcategories"]:
        for sib in sc["adjacent_to"]["similar"]:
            forward_similar.add((sc["name"], sib))

    # For every (A, B) in similar, ensure (B, A) is also in similar
    for a, b in forward_similar:
        if (b, a) in forward_similar:
            continue  # already symmetric
        rev_entry = by_name[b]
        # If a is currently in b's `related`, demote (remove from related, add to similar)
        if a in rev_entry["adjacent_to"]["related"]:
            rev_entry["adjacent_to"]["related"].remove(a)
            demoted += 1
        # Add a to b's similar (idempotent: skip if already there for any reason)
        if a not in rev_entry["adjacent_to"]["similar"]:
            rev_entry["adjacent_to"]["similar"].append(a)
            added += 1

    return added, demoted


# ---------------------------------------------------------------------------
# Idempotency: flatten any existing typed structure back to a list
# ---------------------------------------------------------------------------


def _flatten_adjacent_to(adj) -> list[str]:
    """Accept either the typed dict form or the flat list form, return flat list."""
    if isinstance(adj, list):
        return list(adj)
    if isinstance(adj, dict):
        return list(adj.get("similar", [])) + list(adj.get("related", []))
    return []


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    defs = yaml.safe_load(DEFS_PATH.read_text())
    taxonomy = yaml.safe_load(TAXONOMY_PATH.read_text())

    canonical = {sub["name"] for cat in taxonomy["categories"] for sub in cat["subcategories"]}
    sub_to_cat = {
        sub["name"]: cat["name"] for cat in taxonomy["categories"] for sub in cat["subcategories"]
    }

    # ----- Step 1: flatten any prior typed form, then clean -----
    broken_dropped = 0
    broken_mapped = 0
    self_loops_removed = 0

    for sc in defs["subcategories"]:
        name = sc["name"]
        adj = _flatten_adjacent_to(sc.get("adjacent_to", []))
        new_adj: list[str] = []
        for a in adj:
            if a == name:
                self_loops_removed += 1
                continue
            if a not in canonical:
                action = BROKEN_REF_MAP.get(a)
                if action == "drop":
                    broken_dropped += 1
                    continue
                if action and action.startswith("map:"):
                    mapped = action.split(":", 1)[1]
                    if mapped not in canonical:
                        raise ValueError(f"Override target {mapped!r} not canonical")
                    if mapped in new_adj or mapped == name:
                        broken_dropped += 1
                        continue
                    new_adj.append(mapped)
                    broken_mapped += 1
                    continue
                raise ValueError(f"Unmapped broken ref {a!r} in entry {name!r}")
            if a in new_adj:
                continue
            new_adj.append(a)
        sc["_adj_flat"] = new_adj  # stash for step 2

    # ----- Step 2: type each edge -----
    def classify(src: str, tgt: str) -> str:
        pair = (src, tgt)
        if pair in CROSS_CAT_SIMILAR_PAIRS:
            return "similar"
        if pair in SAME_CAT_RELATED_PAIRS:
            return "related"
        return "similar" if sub_to_cat[src] == sub_to_cat[tgt] else "related"

    similar_count = 0
    related_count = 0
    for sc in defs["subcategories"]:
        src = sc["name"]
        sim: list[str] = []
        rel: list[str] = []
        for tgt in sc.pop("_adj_flat"):
            if classify(src, tgt) == "similar":
                sim.append(tgt)
                similar_count += 1
            else:
                rel.append(tgt)
                related_count += 1
        sc["adjacent_to"] = {"similar": sim, "related": rel}

    # ----- Step 2b: enforce symmetry on similar edges -----
    sym_added, sym_demoted = _enforce_symmetry(defs)
    similar_count += sym_added
    related_count -= sym_demoted

    # ----- Step 3: emit canonical YAML (preserve grouping by category) -----
    cat_boundaries = []
    idx = 0
    for cat in taxonomy["categories"]:
        start = idx
        idx += len(cat["subcategories"])
        cat_boundaries.append((start, idx, cat["name"]))

    _write_yaml(defs, cat_boundaries)

    # ----- Report -----
    print(f"Step 1: broken refs dropped: {broken_dropped}")
    print(f"Step 1: broken refs mapped:  {broken_mapped}")
    print(f"Step 1: self-loops removed:  {self_loops_removed}")
    print(f"Step 2: edges typed:         {similar_count + related_count}")
    print(f"           similar:          {similar_count}")
    print(f"           related:          {related_count}")
    print(f"Step 2b: symmetry added:     {sym_added}")
    print(f"Step 2b: symmetry demoted:   {sym_demoted}")
    return 0


def _emit_entry(entry: dict, indent: str = "  ") -> str:
    lines = [
        f'{indent}- name: "{entry["name"]}"',
        f"{indent}  nature: {entry['nature']}",
        f"{indent}  confidence: {entry['confidence']}",
        f'{indent}  one_line: "{entry["one_line"].replace(chr(34), chr(92) + chr(34))}"',
    ]
    for field in ("applies_when", "does_not_apply_when", "user_signals"):
        lines.append(f"{indent}  {field}:")
        for item in entry[field]:
            esc = item.replace('"', '\\"')
            lines.append(f'{indent}    - "{esc}"')
    lines.append(f"{indent}  adjacent_to:")
    for rel_key in ("similar", "related"):
        items = entry["adjacent_to"].get(rel_key, [])
        if items:
            lines.append(f"{indent}    {rel_key}:")
            for item in items:
                esc = item.replace('"', '\\"')
                lines.append(f'{indent}      - "{esc}"')
        else:
            lines.append(f"{indent}    {rel_key}: []")
    # Preserve disambiguation field if Pass B has already populated it.
    # Pass A doesn't manage disambiguation content, but must not drop it on re-emit.
    disambig = entry.get("disambiguation")
    if isinstance(disambig, dict) and disambig:
        lines.append(f"{indent}  disambiguation:")
        for sibling in entry["adjacent_to"]["similar"]:
            if sibling in disambig:
                key_esc = sibling.replace('"', '\\"')
                val_esc = disambig[sibling].replace('"', '\\"')
                lines.append(f'{indent}    "{key_esc}": "{val_esc}"')
    lines.append(f"{indent}  elements:")
    for elem in (
        "threat",
        "event",
        "operational_artifacts",
        "mitigations_controls",
        "regulatory_standards",
        "research",
    ):
        e = entry["elements"][elem]
        lines.append(f"{indent}    {elem}:")
        lines.append(f"{indent}      population: {e['population']}")
        if "notes" in e:
            notes = e["notes"].replace('"', '\\"')
            lines.append(f'{indent}      notes: "{notes}"')
    return "\n".join(lines)


def _write_yaml(defs: dict, cat_boundaries: list[tuple[int, int, str]]) -> None:
    header = (
        "# AI Risk Taxonomy — Subcategory Definitions (v2.1)\n"
        "# =====================================================\n"
        "# Expert-revised v2 with: nature, confidence, applies_when, does_not_apply_when,\n"
        "# user_signals, adjacent_to (typed: similar / related), and elements (6 populations).\n"
        "#\n"
        "# adjacent_to.similar: close concepts the matcher might consider switching to\n"
        "# adjacent_to.related: connected but distinct concepts the matcher might mention\n"
        "#\n"
        "# Names match taxonomy.yaml exactly — this is the interface contract.\n"
        "#\n"
        "# Version: 2.1\n"
        "\n"
        'version: "2.1"\n'
    )
    out = [header, "subcategories:", ""]
    for start, end, title in cat_boundaries:
        out.append("  # " + "═" * 68)
        out.append(f"  # {title}")
        out.append("  # " + "═" * 68)
        out.append("")
        for i in range(start, end):
            out.append(_emit_entry(defs["subcategories"][i]))
            out.append("")
    DEFS_PATH.write_text("\n".join(out))


if __name__ == "__main__":
    raise SystemExit(main())
